version: "3.7"

services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yatzy
      MYSQL_USER: yatzy
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./yatzy.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  data: {}
